### ISSUE TITLE
License is missing?

### ISSUE THREAD

**Issue by kasra-hosseini** [spring-epfl/synthetic_data_release#1]
Hi, is it possible to add a license to the repository? (It seems that at least [one code](https://github.com/spring-epfl/synthetic_data_release/blob/master/generative_models/data_synthesiser.py) has been already licensed.)

**Comment by kasra-hosseini** [comment]
Hi again, thank you for releasing these codes. I just wanted to let you know that in our [QUIPP-pipeline repo](https://github.com/alan-turing-institute/QUIPP-pipeline), we use a forked version of your repo found here: https://github.com/kasra-hosseini/synthetic_data_release

The changes in the forked version (https://github.com/kasra-hosseini/synthetic_data_release) are minimal and can be found here: https://github.com/spring-epfl/synthetic_data_release/compare/master...kasra-hosseini:develop

Please let us know in case there are any licensing issues in either forking your repo or using it in our QUIPP-pipeline repo.

**Comment by laurent-girod** [comment]
Hello,

We are sorry for our late reply.

Thank you for reporting this issue. We released the code under BSD 3 clauses license.

Please use our code as you like! :-)

**Comment by kasra-hosseini** [comment]
@laurent-girod Many thanks for your reply :). I close the issue.
